fos_rest:
    zone:
        - { path: ^/api/* }
    exception:
        enabled: true
    disable_csrf_role: IS_AUTHENTICATED_ANONYMOUSLY
    view:
        view_response_listener: force
        formats:
            json: true
    body_converter:
        enabled: true
        validate: true
    param_fetcher_listener: true
    format_listener:
        enabled: true
        rules:
            - { path: ^/api, fallback_format: 'json', priorities: [ json ] }
            - { path: '^/', fallback_format: html, prefer_extension: true, priorities: [ 'html', '*/*' ] }
