nelmio_api_doc:
    documentation:
        info:
            title: Shopping list API
            description: This API is used to create/edit/delete shopping list!
            version: 1.0.0
        components:
            securitySchemes:
                bearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            -   bearerAuth: [ ]
        paths:
            /api/login:
                post:
                    tags:
                        - Authentication
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        email:
                                            type: string
                                        password:
                                            type: string
                    responses:
                        '200':
                            description: Login successful
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                        '401':
                            description: Invalid credentials
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            code:
                                                type: int
                                            message:
                                                type: string
    areas:
        path_patterns:
            - ^/api(?!/doc$)
