nelmio_api_doc:
    documentation:
        info:
            title: Shopping list API
            description: This API is used to create/edit/delete shopping list!
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
