security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        user:
            entity:
                class: App\Entity\User
                property: email
        admin:
            memory:
                users:
                    root@root.com: { password: '$2y$13$/Xlpy/A16MRxUm23jSFUo.KLCPFbOLpPDOriLuTkWKZ1xasSst7pa', roles: [ 'ROLE_SUPER_ADMIN', 'ROLE_ADMIN' ] }
        users:
            chain:
                providers: [ admin, user ]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login
            provider: users
            stateless: true
            json_login:
                check_path: /api/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: email
        api:
            pattern: ^/api
            provider: users
            stateless: true
            jwt: ~
    access_control:
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
