parameters:
    default_env: 'prod'
    APP_ENV: '%env(default:default_env:APP_ENV)%'
    d_false: 'false'
    APP_JSON_DEBUG: '%env(bool:default:d_false:APP_JSON_DEBUG)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Response\Body\ExceptionBody:
        arguments:
            $environment: '%APP_ENV%'
            $debug: '%APP_JSON_DEBUG%'